# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr1 = np.array(my_mat)

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [19]:
#to get zeroes

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((1,1))

array([[1.]])

In [24]:
np.ones((100,90))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [25]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [27]:
np.eye(4)                         ## square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# Obtaining random uniform distributed numbers as list

In [29]:
np.random.rand(5)

array([0.52865391, 0.35167638, 0.2390751 , 0.68862764, 0.90341803])

In [30]:
np.random.rand(5,5) ## obtaining random unifrom distributed numbers in a list

array([[0.3187398 , 0.06338906, 0.27243295, 0.59348702, 0.4854726 ],
       [0.23461274, 0.19047638, 0.4632627 , 0.17697855, 0.82266092],
       [0.41172866, 0.67349486, 0.52765532, 0.93950578, 0.93267329],
       [0.23590283, 0.91555277, 0.01126008, 0.94059182, 0.42304926],
       [0.60887294, 0.45750243, 0.23657978, 0.67024727, 0.85590119]])

In [31]:
np.random.randn(5)                           ## using randn to get standard normally distributed numbers(around zero)

array([-0.79663056,  0.16845609, -0.23765609,  1.63410115, -0.15944916])

In [32]:
## randint. Returns random integers from low to high.

In [34]:
np.random.randint(0,100)

86

In [35]:
np.random.randint(0,100,60)

array([19, 10, 98, 80, 94, 58, 47, 87, 38, 17, 71, 62, 86, 81, 11, 93, 36,
       14, 74,  1, 57, 27, 65, 36, 68,  0, 92, 46, 24, 62, 28, 72, 90, 12,
       88, 61, 34, 14, 12, 44, 71, 32, 55, 95, 21,  9, 93, 99, 73, 46, 17,
       94, 85, 46, 21, 58, 96, 76, 17, 95])

## Attributes and Methods

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arran = np.random.randint(0,50,10)

In [41]:
arran

array([10, 29, 49, 49, 34, 24, 38, 13, 23, 42])

In [42]:
## reshaping an array

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arran

array([10, 29, 49, 49, 34, 24, 38, 13, 23, 42])

In [47]:
arran.max()  ## gives maximum value of the array

49

In [48]:
arran.min() ## returns the minimum value of the array

10

In [50]:
arran.argmax()              ##this line returns the position of the maimum value

2

In [51]:
arran.argmin()       ## returns the position of the minimum value in the array

0

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr = arr.reshape(5,5)

In [54]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr.dtype              ## returns the data type of the array

dtype('int32')

In [58]:
from numpy.random import randint

In [59]:
randint(5,12)

8