In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[8:]

array([ 8,  9, 10])

In [10]:
arr[0:5] =100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slice_of_array = arr[0:6]

In [25]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [26]:
slice_of_array[:]

array([0, 1, 2, 3, 4, 5])

In [27]:
slice_of_array[:] = 101

In [28]:
slice_of_array

array([101, 101, 101, 101, 101, 101])

In [29]:
arr

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [30]:
arr_copy = arr.copy()

In [31]:
arr_copy

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [40]:
arr_copy = arr.copy()

In [41]:
arr_copy = 101

In [42]:
arr_copy

101

In [43]:
arr_copy[:] = 101

TypeError: 'int' object does not support item assignment

In [44]:
arr_copy = arr.copy()

In [45]:
arr

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [46]:
arr_copy[:] = 101

In [47]:
arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [48]:
arr

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

# NumPy Indexing and Selection

In [49]:
#Making a 2d array

In [61]:
array_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [62]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
array_2d[0,2]             ## to obtain digit 15

15

In [65]:
array_2d[0]

array([ 5, 10, 15])

In [66]:
array_2d[2][1]

40

In [67]:
array_2d[2,1]

40

In [69]:
array_2d[1,2]

30

In [70]:
array_2d[:1,:2]

array([[ 5, 10]])

In [71]:
array_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [76]:
bool_arr = arr > 5

In [77]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [78]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [79]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr<3]

array([0, 1, 2])

In [81]:
#Practice

In [82]:
arr = np.arange(50).reshape(5,10)

In [83]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [85]:
arr[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [91]:
arr[4,6]

46

In [95]:
arr[3:5,6:8]

array([[36, 37],
       [46, 47]])